### ISSUE TITLE
Sum of middle numbers from multidigit

### ISSUE THREAD

**Issue by roshan-acharya** [akshatkumar27/Hactoberfest_Challenge#67]
Assign me

**Comment by roshan-acharya** [comment]
@akshatkumar27 You need to add contributing.md file with rule as mentioned in hactoberfest website . Kindly add it !!

**Comment by Jayesh-JainX** [comment]
can you share some sample input and output of this

**Comment by Jayesh-JainX** [comment]
need some sample input and outputs for this issue

**Comment by roshan-acharya** [comment]
@Jayesh-JainX if you enter multidigit 2345 you will get sum of middle digits i.e. 3+4

**Comment by Jayesh-JainX** [comment]
@roshan-acharya what about 12345

**Comment by roshan-acharya** [comment]
@Jayesh-JainX  2+3+4
